<?php

$cityzen = [
    'app_name' => 'CityZen',
    'city_name' => 'Municipalite de Tunis',
    'current_date' => 'Lundi 6 Avr. 2026',
    'user' => [
        'name' => 'Admin',
        'initials' => 'AD',
    ],
    'stats' => [
        'reports' => [
            'value' => 142,
            'label' => 'Signalements actifs',
            'trend' => '+12 cette semaine',
        ],
        'projects' => [
            'value' => 38,
            'label' => 'Projets en vote',
            'trend' => 'stable',
        ],
        'resolution' => [
            'value' => '87%',
            'label' => 'Taux de resolution',
            'trend' => '+3% ce mois',
        ],
        'alerts' => [
            'value' => 5,
            'label' => 'Alertes urgentes',
            'trend' => '+2 aujourd\'hui',
        ],
    ],
    'districts' => [
        ['name' => 'Centre-ville', 'value' => 82, 'tone' => 'green'],
        ['name' => 'Menzah', 'value' => 67, 'tone' => 'green'],
        ['name' => 'Bab El Bhar', 'value' => 54, 'tone' => 'amber'],
        ['name' => 'La Marsa', 'value' => 43, 'tone' => 'orange'],
        ['name' => 'Ariana', 'value' => 31, 'tone' => 'red'],
    ],
    'weekly_reports' => [
        ['day' => 'Lun', 'value' => 14, 'tone' => 'green-outline'],
        ['day' => 'Mar', 'value' => 28, 'tone' => 'soft-green'],
        ['day' => 'Mer', 'value' => 20, 'tone' => 'green-outline'],
        ['day' => 'Jeu', 'value' => 38, 'tone' => 'green'],
        ['day' => 'Ven', 'value' => 30, 'tone' => 'soft-green'],
        ['day' => 'Sam', 'value' => 44, 'tone' => 'orange'],
        ['day' => 'Dim', 'value' => 28, 'tone' => 'soft-green'],
    ],
    'weekly_summary' => [
        'resolved' => 124,
        'pending' => 18,
    ],
    'services' => [
        [
            'icon' => 'SG',
            'title' => 'Signalement',
            'description' => '142 incidents',
            'status' => '',
            'highlight' => false,
        ],
        [
            'icon' => 'PT',
            'title' => 'Participation',
            'description' => '38 projets',
            'status' => 'Actif',
            'highlight' => true,
        ],
        [
            'icon' => 'AL',
            'title' => 'Alertes',
            'description' => '5 urgences',
            'status' => '',
            'highlight' => false,
        ],
    ],
    'recent_reports' => [
        [
            'title' => 'Nid-de-poule - Av. Bourguiba',
            'meta' => 'Signale il y a 2 h - Tunis Centre',
            'status' => 'Urgent',
            'severity' => 'urgent',
            'category' => 'Voirie',
            'district' => 'Centre-ville',
            'date' => 'Auj. 09:14',
        ],
        [
            'title' => 'Lampadaire casse - Rue de la Liberte',
            'meta' => 'Signale il y a 5 h - Bab El Bhar',
            'status' => 'En cours',
            'severity' => 'progress',
            'category' => 'Eclairage',
            'district' => 'Bab El Bhar',
            'date' => 'Auj. 07:30',
        ],
        [
            'title' => 'Depot sauvage - Quartier Menzah',
            'meta' => 'Signale hier - Menzah 6',
            'status' => 'Nouveau',
            'severity' => 'new',
            'category' => 'Dechets',
            'district' => 'Menzah',
            'date' => 'Hier 18:45',
        ],
        [
            'title' => 'Fuite d\'eau - Rue Ibn Khaldoun',
            'meta' => 'Signale hier - La Marsa',
            'status' => 'Resolue',
            'severity' => 'done',
            'category' => 'Eau',
            'district' => 'La Marsa',
            'date' => 'Hier 14:20',
        ],
    ],
    'admin_menu' => [
        ['key' => 'public', 'label' => 'Site public', 'url' => '/index.php'],
        ['key' => 'portail', 'label' => 'Portail municipal', 'url' => '/admin/index.php'],
        ['key' => 'dashboard', 'label' => 'Tableau de bord', 'url' => '/admin/dashboard.php'],
        ['key' => 'reports', 'label' => 'Signalements', 'url' => '#signalements'],
        ['key' => 'projects', 'label' => 'Projets', 'url' => '#projets'],
        ['key' => 'air', 'label' => 'Qualite air', 'url' => '#qualite-air'],
        ['key' => 'equipment', 'label' => 'Equipement', 'url' => '/admin/equipment.php'],
        ['key' => 'eq-tickets', 'label' => 'Tickets equipement', 'url' => '/admin/equipment_tickets.php'],
        ['key' => 'waste', 'label' => 'Dechets', 'url' => '#dechets'],
        ['key' => 'citizens', 'label' => 'Citoyens', 'url' => '#citoyens'],
        ['key' => 'users', 'label' => 'Utilisateurs', 'url' => '/admin/users.php'],
        ['key' => 'settings', 'label' => 'Parametres', 'url' => '/admin/settings.php'],
        ['key' => 'logout', 'label' => 'Deconnexion', 'url' => '/admin/logout.php'],
    ],
    'public_menu' => [
        ['key' => 'home', 'label' => 'Accueil', 'url' => '/index.php'],
        ['key' => 'reports', 'label' => 'Signalements', 'url' => '#signalements'],
        ['key' => 'projects', 'label' => 'Projets', 'url' => '#projets'],
        ['key' => 'equipment', 'label' => 'Equipement', 'url' => '/equipment/index.php'],
        ['key' => 'portail', 'label' => 'Portail municipal', 'url' => '/admin/index.php'],
        ['key' => 'back-office', 'label' => 'Back-office', 'url' => '/admin/dashboard.php'],
    ],
];
